import = ["/Users/rms/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

# [shell]
# program = "/bin/zsh"
# args = ["-l", "-c", "tmux attach -t main || tmux new -s main"]

[cursor]
unfocused_hollow = true

[cursor.style]
shape = "Block"

[cursor.vi_mode_style]
blinking = "Off"
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 15.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[mouse]
hide_when_typing = true

[colors]
transparent_background_colors = true

[window]
blur = true
decorations = "buttonless"
dynamic_title = true
opacity = 0.85

[window.padding]
x = 25
y = 20
